---
apiVersion: v1
kind: Pod
metadata:
 name: mysql-pod
 labels:
  author: intelliq
  type: back-end
spec:
 containers:
  - name: mydb
    image: mysql:5
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: intelliq
